//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class About
{
    public int Id { get; set; }
    public string MessageOne { get; set; }
    public string MessageTwo { get; set; }
    public string MessageThree { get; set; }
    public string ImageURLOne { get; set; }
    public string ImageURLTwo { get; set; }
    public string ImageURLThree { get; set; }
    public Nullable<System.DateTime> EnteredOn { get; set; }
    public Nullable<int> EnteredBy { get; set; }
    public Nullable<System.DateTime> UpdatedOn { get; set; }
    public Nullable<int> UpdatedBy { get; set; }
}

public partial class Home
{
    public int Id { get; set; }
    public string MessageOne { get; set; }
    public string MessageTwo { get; set; }
    public string MessageThree { get; set; }
    public string ImageURLOne { get; set; }
    public string ImageURLTwo { get; set; }
    public string ImageURLThree { get; set; }
    public Nullable<System.DateTime> EnteredOn { get; set; }
    public Nullable<int> EnteredBy { get; set; }
    public Nullable<System.DateTime> UpdatedOn { get; set; }
    public Nullable<int> UpdatedBy { get; set; }
}

public partial class Posting
{
    public Posting()
    {
        this.TradeRequests = new HashSet<TradeRequest>();
    }

    public int Id { get; set; }
    public string ISBN { get; set; }
    public string Description { get; set; }
    public string Major { get; set; }
    public string Title { get; set; }
    public string Author { get; set; }
    public string Price { get; set; }
    public string Condition { get; set; }
    public string ImageURL { get; set; }
    public string EnteredOn { get; set; }
    public string UpdatedOn { get; set; }
    public Nullable<int> UserId { get; set; }

    public virtual User User { get; set; }
    public virtual ICollection<TradeRequest> TradeRequests { get; set; }
}

public partial class TradeRequest
{
    public int Id { get; set; }
    public Nullable<int> Status { get; set; }
    public Nullable<System.DateTime> RequestDate { get; set; }
    public Nullable<int> PostingId { get; set; }
    public Nullable<int> UserId { get; set; }

    public virtual Posting Posting { get; set; }
    public virtual User User { get; set; }
}

public partial class User
{
    public User()
    {
        this.Postings = new HashSet<Posting>();
        this.TradeRequests = new HashSet<TradeRequest>();
        this.UserReviews = new HashSet<UserReview>();
        this.UserReviews1 = new HashSet<UserReview>();
    }

    public int Id { get; set; }
    public string Email { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Password { get; set; }
    public string City { get; set; }
    public string Phone { get; set; }
    public string CurrentCollege { get; set; }
    public string ImageURL { get; set; }
    public string Description { get; set; }
    public Nullable<System.DateTime> CreatedOn { get; set; }

    public virtual ICollection<Posting> Postings { get; set; }
    public virtual ICollection<TradeRequest> TradeRequests { get; set; }
    public virtual ICollection<UserReview> UserReviews { get; set; }
    public virtual ICollection<UserReview> UserReviews1 { get; set; }
}

public partial class UserReview
{
    public int Id { get; set; }
    public Nullable<double> Rating { get; set; }
    public string Comment { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<int> FromUserId { get; set; }
    public Nullable<int> ForUserId { get; set; }

    public virtual User User { get; set; }
    public virtual User User1 { get; set; }
}
