//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BookExchangeModel", "FK_Postings_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BookExchangeModel.User), "Postings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BookExchangeModel.Posting), true)]
[assembly: EdmRelationshipAttribute("BookExchangeModel", "FK_TradeRequests_Postings", "Postings", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BookExchangeModel.Posting), "TradeRequests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BookExchangeModel.TradeRequest), true)]
[assembly: EdmRelationshipAttribute("BookExchangeModel", "FK_TradeRequests_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BookExchangeModel.User), "TradeRequests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BookExchangeModel.TradeRequest), true)]
[assembly: EdmRelationshipAttribute("BookExchangeModel", "FK_UserReviews_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BookExchangeModel.User), "UserReviews", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BookExchangeModel.UserReview), true)]
[assembly: EdmRelationshipAttribute("BookExchangeModel", "FK_UserReviews_Users1", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BookExchangeModel.User), "UserReviews", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BookExchangeModel.UserReview), true)]

#endregion

namespace BookExchangeModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BookExchangeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BookExchangeEntities object using the connection string found in the 'BookExchangeEntities' section of the application configuration file.
        /// </summary>
        public BookExchangeEntities() : base("name=BookExchangeEntities", "BookExchangeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BookExchangeEntities object.
        /// </summary>
        public BookExchangeEntities(string connectionString) : base(connectionString, "BookExchangeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BookExchangeEntities object.
        /// </summary>
        public BookExchangeEntities(EntityConnection connection) : base(connection, "BookExchangeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<About> Abouts
        {
            get
            {
                if ((_Abouts == null))
                {
                    _Abouts = base.CreateObjectSet<About>("Abouts");
                }
                return _Abouts;
            }
        }
        private ObjectSet<About> _Abouts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Home> Homes
        {
            get
            {
                if ((_Homes == null))
                {
                    _Homes = base.CreateObjectSet<Home>("Homes");
                }
                return _Homes;
            }
        }
        private ObjectSet<Home> _Homes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Posting> Postings
        {
            get
            {
                if ((_Postings == null))
                {
                    _Postings = base.CreateObjectSet<Posting>("Postings");
                }
                return _Postings;
            }
        }
        private ObjectSet<Posting> _Postings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TradeRequest> TradeRequests
        {
            get
            {
                if ((_TradeRequests == null))
                {
                    _TradeRequests = base.CreateObjectSet<TradeRequest>("TradeRequests");
                }
                return _TradeRequests;
            }
        }
        private ObjectSet<TradeRequest> _TradeRequests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserReview> UserReviews
        {
            get
            {
                if ((_UserReviews == null))
                {
                    _UserReviews = base.CreateObjectSet<UserReview>("UserReviews");
                }
                return _UserReviews;
            }
        }
        private ObjectSet<UserReview> _UserReviews;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Abouts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAbouts(About about)
        {
            base.AddObject("Abouts", about);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Homes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHomes(Home home)
        {
            base.AddObject("Homes", home);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Postings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPostings(Posting posting)
        {
            base.AddObject("Postings", posting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TradeRequests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTradeRequests(TradeRequest tradeRequest)
        {
            base.AddObject("TradeRequests", tradeRequest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserReviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserReviews(UserReview userReview)
        {
            base.AddObject("UserReviews", userReview);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BookExchangeModel", Name="About")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class About : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new About object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static About CreateAbout(global::System.Int32 id)
        {
            About about = new About();
            about.Id = id;
            return about;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageOne
        {
            get
            {
                return _MessageOne;
            }
            set
            {
                OnMessageOneChanging(value);
                ReportPropertyChanging("MessageOne");
                _MessageOne = StructuralObject.SetValidValue(value, true, "MessageOne");
                ReportPropertyChanged("MessageOne");
                OnMessageOneChanged();
            }
        }
        private global::System.String _MessageOne;
        partial void OnMessageOneChanging(global::System.String value);
        partial void OnMessageOneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageTwo
        {
            get
            {
                return _MessageTwo;
            }
            set
            {
                OnMessageTwoChanging(value);
                ReportPropertyChanging("MessageTwo");
                _MessageTwo = StructuralObject.SetValidValue(value, true, "MessageTwo");
                ReportPropertyChanged("MessageTwo");
                OnMessageTwoChanged();
            }
        }
        private global::System.String _MessageTwo;
        partial void OnMessageTwoChanging(global::System.String value);
        partial void OnMessageTwoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageThree
        {
            get
            {
                return _MessageThree;
            }
            set
            {
                OnMessageThreeChanging(value);
                ReportPropertyChanging("MessageThree");
                _MessageThree = StructuralObject.SetValidValue(value, true, "MessageThree");
                ReportPropertyChanged("MessageThree");
                OnMessageThreeChanged();
            }
        }
        private global::System.String _MessageThree;
        partial void OnMessageThreeChanging(global::System.String value);
        partial void OnMessageThreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURLOne
        {
            get
            {
                return _ImageURLOne;
            }
            set
            {
                OnImageURLOneChanging(value);
                ReportPropertyChanging("ImageURLOne");
                _ImageURLOne = StructuralObject.SetValidValue(value, true, "ImageURLOne");
                ReportPropertyChanged("ImageURLOne");
                OnImageURLOneChanged();
            }
        }
        private global::System.String _ImageURLOne;
        partial void OnImageURLOneChanging(global::System.String value);
        partial void OnImageURLOneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURLTwo
        {
            get
            {
                return _ImageURLTwo;
            }
            set
            {
                OnImageURLTwoChanging(value);
                ReportPropertyChanging("ImageURLTwo");
                _ImageURLTwo = StructuralObject.SetValidValue(value, true, "ImageURLTwo");
                ReportPropertyChanged("ImageURLTwo");
                OnImageURLTwoChanged();
            }
        }
        private global::System.String _ImageURLTwo;
        partial void OnImageURLTwoChanging(global::System.String value);
        partial void OnImageURLTwoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURLThree
        {
            get
            {
                return _ImageURLThree;
            }
            set
            {
                OnImageURLThreeChanging(value);
                ReportPropertyChanging("ImageURLThree");
                _ImageURLThree = StructuralObject.SetValidValue(value, true, "ImageURLThree");
                ReportPropertyChanged("ImageURLThree");
                OnImageURLThreeChanged();
            }
        }
        private global::System.String _ImageURLThree;
        partial void OnImageURLThreeChanging(global::System.String value);
        partial void OnImageURLThreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EnteredOn
        {
            get
            {
                return _EnteredOn;
            }
            set
            {
                OnEnteredOnChanging(value);
                ReportPropertyChanging("EnteredOn");
                _EnteredOn = StructuralObject.SetValidValue(value, "EnteredOn");
                ReportPropertyChanged("EnteredOn");
                OnEnteredOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _EnteredOn;
        partial void OnEnteredOnChanging(Nullable<global::System.DateTime> value);
        partial void OnEnteredOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EnteredBy
        {
            get
            {
                return _EnteredBy;
            }
            set
            {
                OnEnteredByChanging(value);
                ReportPropertyChanging("EnteredBy");
                _EnteredBy = StructuralObject.SetValidValue(value, "EnteredBy");
                ReportPropertyChanged("EnteredBy");
                OnEnteredByChanged();
            }
        }
        private Nullable<global::System.Int32> _EnteredBy;
        partial void OnEnteredByChanging(Nullable<global::System.Int32> value);
        partial void OnEnteredByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedOn
        {
            get
            {
                return _UpdatedOn;
            }
            set
            {
                OnUpdatedOnChanging(value);
                ReportPropertyChanging("UpdatedOn");
                _UpdatedOn = StructuralObject.SetValidValue(value, "UpdatedOn");
                ReportPropertyChanged("UpdatedOn");
                OnUpdatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedOn;
        partial void OnUpdatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, "UpdatedBy");
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdatedBy;
        partial void OnUpdatedByChanging(Nullable<global::System.Int32> value);
        partial void OnUpdatedByChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BookExchangeModel", Name="Home")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Home : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Home object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Home CreateHome(global::System.Int32 id)
        {
            Home home = new Home();
            home.Id = id;
            return home;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageOne
        {
            get
            {
                return _MessageOne;
            }
            set
            {
                OnMessageOneChanging(value);
                ReportPropertyChanging("MessageOne");
                _MessageOne = StructuralObject.SetValidValue(value, true, "MessageOne");
                ReportPropertyChanged("MessageOne");
                OnMessageOneChanged();
            }
        }
        private global::System.String _MessageOne;
        partial void OnMessageOneChanging(global::System.String value);
        partial void OnMessageOneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageTwo
        {
            get
            {
                return _MessageTwo;
            }
            set
            {
                OnMessageTwoChanging(value);
                ReportPropertyChanging("MessageTwo");
                _MessageTwo = StructuralObject.SetValidValue(value, true, "MessageTwo");
                ReportPropertyChanged("MessageTwo");
                OnMessageTwoChanged();
            }
        }
        private global::System.String _MessageTwo;
        partial void OnMessageTwoChanging(global::System.String value);
        partial void OnMessageTwoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageThree
        {
            get
            {
                return _MessageThree;
            }
            set
            {
                OnMessageThreeChanging(value);
                ReportPropertyChanging("MessageThree");
                _MessageThree = StructuralObject.SetValidValue(value, true, "MessageThree");
                ReportPropertyChanged("MessageThree");
                OnMessageThreeChanged();
            }
        }
        private global::System.String _MessageThree;
        partial void OnMessageThreeChanging(global::System.String value);
        partial void OnMessageThreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURLOne
        {
            get
            {
                return _ImageURLOne;
            }
            set
            {
                OnImageURLOneChanging(value);
                ReportPropertyChanging("ImageURLOne");
                _ImageURLOne = StructuralObject.SetValidValue(value, true, "ImageURLOne");
                ReportPropertyChanged("ImageURLOne");
                OnImageURLOneChanged();
            }
        }
        private global::System.String _ImageURLOne;
        partial void OnImageURLOneChanging(global::System.String value);
        partial void OnImageURLOneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURLTwo
        {
            get
            {
                return _ImageURLTwo;
            }
            set
            {
                OnImageURLTwoChanging(value);
                ReportPropertyChanging("ImageURLTwo");
                _ImageURLTwo = StructuralObject.SetValidValue(value, true, "ImageURLTwo");
                ReportPropertyChanged("ImageURLTwo");
                OnImageURLTwoChanged();
            }
        }
        private global::System.String _ImageURLTwo;
        partial void OnImageURLTwoChanging(global::System.String value);
        partial void OnImageURLTwoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURLThree
        {
            get
            {
                return _ImageURLThree;
            }
            set
            {
                OnImageURLThreeChanging(value);
                ReportPropertyChanging("ImageURLThree");
                _ImageURLThree = StructuralObject.SetValidValue(value, true, "ImageURLThree");
                ReportPropertyChanged("ImageURLThree");
                OnImageURLThreeChanged();
            }
        }
        private global::System.String _ImageURLThree;
        partial void OnImageURLThreeChanging(global::System.String value);
        partial void OnImageURLThreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EnteredOn
        {
            get
            {
                return _EnteredOn;
            }
            set
            {
                OnEnteredOnChanging(value);
                ReportPropertyChanging("EnteredOn");
                _EnteredOn = StructuralObject.SetValidValue(value, "EnteredOn");
                ReportPropertyChanged("EnteredOn");
                OnEnteredOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _EnteredOn;
        partial void OnEnteredOnChanging(Nullable<global::System.DateTime> value);
        partial void OnEnteredOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EnteredBy
        {
            get
            {
                return _EnteredBy;
            }
            set
            {
                OnEnteredByChanging(value);
                ReportPropertyChanging("EnteredBy");
                _EnteredBy = StructuralObject.SetValidValue(value, "EnteredBy");
                ReportPropertyChanged("EnteredBy");
                OnEnteredByChanged();
            }
        }
        private Nullable<global::System.Int32> _EnteredBy;
        partial void OnEnteredByChanging(Nullable<global::System.Int32> value);
        partial void OnEnteredByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdatedOn
        {
            get
            {
                return _UpdatedOn;
            }
            set
            {
                OnUpdatedOnChanging(value);
                ReportPropertyChanging("UpdatedOn");
                _UpdatedOn = StructuralObject.SetValidValue(value, "UpdatedOn");
                ReportPropertyChanged("UpdatedOn");
                OnUpdatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdatedOn;
        partial void OnUpdatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, "UpdatedBy");
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private Nullable<global::System.Int32> _UpdatedBy;
        partial void OnUpdatedByChanging(Nullable<global::System.Int32> value);
        partial void OnUpdatedByChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BookExchangeModel", Name="Posting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Posting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Posting object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Posting CreatePosting(global::System.Int32 id)
        {
            Posting posting = new Posting();
            posting.Id = id;
            return posting;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                OnISBNChanging(value);
                ReportPropertyChanging("ISBN");
                _ISBN = StructuralObject.SetValidValue(value, true, "ISBN");
                ReportPropertyChanged("ISBN");
                OnISBNChanged();
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Major
        {
            get
            {
                return _Major;
            }
            set
            {
                OnMajorChanging(value);
                ReportPropertyChanging("Major");
                _Major = StructuralObject.SetValidValue(value, true, "Major");
                ReportPropertyChanged("Major");
                OnMajorChanged();
            }
        }
        private global::System.String _Major;
        partial void OnMajorChanging(global::System.String value);
        partial void OnMajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true, "Title");
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true, "Author");
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, true, "Price");
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.String _Price;
        partial void OnPriceChanging(global::System.String value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Condition
        {
            get
            {
                return _Condition;
            }
            set
            {
                OnConditionChanging(value);
                ReportPropertyChanging("Condition");
                _Condition = StructuralObject.SetValidValue(value, true, "Condition");
                ReportPropertyChanged("Condition");
                OnConditionChanged();
            }
        }
        private global::System.String _Condition;
        partial void OnConditionChanging(global::System.String value);
        partial void OnConditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, true, "ImageURL");
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EnteredOn
        {
            get
            {
                return _EnteredOn;
            }
            set
            {
                OnEnteredOnChanging(value);
                ReportPropertyChanging("EnteredOn");
                _EnteredOn = StructuralObject.SetValidValue(value, true, "EnteredOn");
                ReportPropertyChanged("EnteredOn");
                OnEnteredOnChanged();
            }
        }
        private global::System.String _EnteredOn;
        partial void OnEnteredOnChanging(global::System.String value);
        partial void OnEnteredOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedOn
        {
            get
            {
                return _UpdatedOn;
            }
            set
            {
                OnUpdatedOnChanging(value);
                ReportPropertyChanging("UpdatedOn");
                _UpdatedOn = StructuralObject.SetValidValue(value, true, "UpdatedOn");
                ReportPropertyChanged("UpdatedOn");
                OnUpdatedOnChanged();
            }
        }
        private global::System.String _UpdatedOn;
        partial void OnUpdatedOnChanging(global::System.String value);
        partial void OnUpdatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserEmail
        {
            get
            {
                return _UserEmail;
            }
            set
            {
                OnUserEmailChanging(value);
                ReportPropertyChanging("UserEmail");
                _UserEmail = StructuralObject.SetValidValue(value, true, "UserEmail");
                ReportPropertyChanged("UserEmail");
                OnUserEmailChanged();
            }
        }
        private global::System.String _UserEmail;
        partial void OnUserEmailChanging(global::System.String value);
        partial void OnUserEmailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookExchangeModel", "FK_Postings_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_Postings_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_Postings_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_Postings_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("BookExchangeModel.FK_Postings_Users", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookExchangeModel", "FK_TradeRequests_Postings", "TradeRequests")]
        public EntityCollection<TradeRequest> TradeRequests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TradeRequest>("BookExchangeModel.FK_TradeRequests_Postings", "TradeRequests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TradeRequest>("BookExchangeModel.FK_TradeRequests_Postings", "TradeRequests", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BookExchangeModel", Name="TradeRequest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TradeRequest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TradeRequest object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static TradeRequest CreateTradeRequest(global::System.Int32 id)
        {
            TradeRequest tradeRequest = new TradeRequest();
            tradeRequest.Id = id;
            return tradeRequest;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RequestDate
        {
            get
            {
                return _RequestDate;
            }
            set
            {
                OnRequestDateChanging(value);
                ReportPropertyChanging("RequestDate");
                _RequestDate = StructuralObject.SetValidValue(value, "RequestDate");
                ReportPropertyChanged("RequestDate");
                OnRequestDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RequestDate;
        partial void OnRequestDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRequestDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PostingId
        {
            get
            {
                return _PostingId;
            }
            set
            {
                OnPostingIdChanging(value);
                ReportPropertyChanging("PostingId");
                _PostingId = StructuralObject.SetValidValue(value, "PostingId");
                ReportPropertyChanged("PostingId");
                OnPostingIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PostingId;
        partial void OnPostingIdChanging(Nullable<global::System.Int32> value);
        partial void OnPostingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserEmail
        {
            get
            {
                return _UserEmail;
            }
            set
            {
                OnUserEmailChanging(value);
                ReportPropertyChanging("UserEmail");
                _UserEmail = StructuralObject.SetValidValue(value, true, "UserEmail");
                ReportPropertyChanged("UserEmail");
                OnUserEmailChanged();
            }
        }
        private global::System.String _UserEmail;
        partial void OnUserEmailChanging(global::System.String value);
        partial void OnUserEmailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookExchangeModel", "FK_TradeRequests_Postings", "Postings")]
        public Posting Posting
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Posting>("BookExchangeModel.FK_TradeRequests_Postings", "Postings").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Posting>("BookExchangeModel.FK_TradeRequests_Postings", "Postings").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Posting> PostingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Posting>("BookExchangeModel.FK_TradeRequests_Postings", "Postings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Posting>("BookExchangeModel.FK_TradeRequests_Postings", "Postings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookExchangeModel", "FK_TradeRequests_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_TradeRequests_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_TradeRequests_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_TradeRequests_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("BookExchangeModel.FK_TradeRequests_Users", "Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BookExchangeModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="email">Initial value of the Email property.</param>
        public static User CreateUser(global::System.String email)
        {
            User user = new User();
            user.Email = email;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                if (_Email != value)
                {
                    OnEmailChanging(value);
                    ReportPropertyChanging("Email");
                    _Email = StructuralObject.SetValidValue(value, false, "Email");
                    ReportPropertyChanged("Email");
                    OnEmailChanged();
                }
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true, "City");
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrentCollege
        {
            get
            {
                return _CurrentCollege;
            }
            set
            {
                OnCurrentCollegeChanging(value);
                ReportPropertyChanging("CurrentCollege");
                _CurrentCollege = StructuralObject.SetValidValue(value, true, "CurrentCollege");
                ReportPropertyChanged("CurrentCollege");
                OnCurrentCollegeChanged();
            }
        }
        private global::System.String _CurrentCollege;
        partial void OnCurrentCollegeChanging(global::System.String value);
        partial void OnCurrentCollegeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, true, "ImageURL");
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value, "CreatedOn");
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookExchangeModel", "FK_Postings_Users", "Postings")]
        public EntityCollection<Posting> Postings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Posting>("BookExchangeModel.FK_Postings_Users", "Postings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Posting>("BookExchangeModel.FK_Postings_Users", "Postings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookExchangeModel", "FK_TradeRequests_Users", "TradeRequests")]
        public EntityCollection<TradeRequest> TradeRequests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TradeRequest>("BookExchangeModel.FK_TradeRequests_Users", "TradeRequests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TradeRequest>("BookExchangeModel.FK_TradeRequests_Users", "TradeRequests", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookExchangeModel", "FK_UserReviews_Users", "UserReviews")]
        public EntityCollection<UserReview> UserReviews
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserReview>("BookExchangeModel.FK_UserReviews_Users", "UserReviews");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserReview>("BookExchangeModel.FK_UserReviews_Users", "UserReviews", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookExchangeModel", "FK_UserReviews_Users1", "UserReviews")]
        public EntityCollection<UserReview> UserReviews1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserReview>("BookExchangeModel.FK_UserReviews_Users1", "UserReviews");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserReview>("BookExchangeModel.FK_UserReviews_Users1", "UserReviews", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BookExchangeModel", Name="UserReview")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserReview : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserReview object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static UserReview CreateUserReview(global::System.Int32 id)
        {
            UserReview userReview = new UserReview();
            userReview.Id = id;
            return userReview;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Rating
        {
            get
            {
                return _Rating;
            }
            set
            {
                OnRatingChanging(value);
                ReportPropertyChanging("Rating");
                _Rating = StructuralObject.SetValidValue(value, "Rating");
                ReportPropertyChanged("Rating");
                OnRatingChanged();
            }
        }
        private Nullable<global::System.Double> _Rating;
        partial void OnRatingChanging(Nullable<global::System.Double> value);
        partial void OnRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true, "Comment");
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromUserEmail
        {
            get
            {
                return _FromUserEmail;
            }
            set
            {
                OnFromUserEmailChanging(value);
                ReportPropertyChanging("FromUserEmail");
                _FromUserEmail = StructuralObject.SetValidValue(value, true, "FromUserEmail");
                ReportPropertyChanged("FromUserEmail");
                OnFromUserEmailChanged();
            }
        }
        private global::System.String _FromUserEmail;
        partial void OnFromUserEmailChanging(global::System.String value);
        partial void OnFromUserEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ForUserEmail
        {
            get
            {
                return _ForUserEmail;
            }
            set
            {
                OnForUserEmailChanging(value);
                ReportPropertyChanging("ForUserEmail");
                _ForUserEmail = StructuralObject.SetValidValue(value, true, "ForUserEmail");
                ReportPropertyChanged("ForUserEmail");
                OnForUserEmailChanged();
            }
        }
        private global::System.String _ForUserEmail;
        partial void OnForUserEmailChanging(global::System.String value);
        partial void OnForUserEmailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookExchangeModel", "FK_UserReviews_Users", "Users")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_UserReviews_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_UserReviews_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_UserReviews_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("BookExchangeModel.FK_UserReviews_Users", "Users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BookExchangeModel", "FK_UserReviews_Users1", "Users")]
        public User User1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_UserReviews_Users1", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_UserReviews_Users1", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BookExchangeModel.FK_UserReviews_Users1", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("BookExchangeModel.FK_UserReviews_Users1", "Users", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
